### ISSUE TITLE
ReadMe not work at all

### ISSUE THREAD

**Issue by yanganto** [jacobsimpson/nvim-example-python-plugin#1]
I install this plugin execute `:exec DoItVimL()` and `:exec DoItPython()`,
the former command print DoItVimL at console but the later command is not found.

**Comment by jacobsimpson** [comment]
I was able to reproduce this issue and solve it by restarting neovim after updating the manifest. Give that a try and let me know if it doesn't correct the problem you encountered.

**Comment by yanganto** [comment]
Sorry about this, my neovim did has problem in communicate with python client. After I reinstall the neovim and the neovim python package, you example is working.
Thanks you.
